# Generated by Django 3.2.8 on 2021-10-31 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
